// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID              pgtype.UUID
	TelegramID      int64
	Username        pgtype.Text
	FirstName       string
	LastName        pgtype.Text
	PhotoUrl        pgtype.Text
	LanguageCode    pgtype.Text
	AllowsWriteToPm pgtype.Bool
	IsPremium       pgtype.Bool
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}
