// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeGiftWithdrawal = `-- name: CompleteGiftWithdrawal :one
UPDATE gifts 
SET status = 'withdrawn', withdrawn_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'withdraw_pending'
RETURNING id, telegram_gift_id, collectible_id, owner_telegram_id, upgrade_message_id, title, slug, price, emoji_id, status, created_at, updated_at, withdrawn_at
`

func (q *Queries) CompleteGiftWithdrawal(ctx context.Context, id pgtype.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, completeGiftWithdrawal, id)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.TelegramGiftID,
		&i.CollectibleID,
		&i.OwnerTelegramID,
		&i.UpgradeMessageID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.EmojiID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const createGift = `-- name: CreateGift :one
INSERT INTO gifts (
    id,
    telegram_gift_id,
    title,
    slug,
    owner_telegram_id,
    upgrade_message_id,
    price,
    emoji_id,
    collectible_id,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, telegram_gift_id, collectible_id, owner_telegram_id, upgrade_message_id, title, slug, price, emoji_id, status, created_at, updated_at, withdrawn_at
`

type CreateGiftParams struct {
	ID               pgtype.UUID
	TelegramGiftID   int64
	Title            string
	Slug             string
	OwnerTelegramID  int64
	UpgradeMessageID int32
	Price            float64
	EmojiID          int64
	CollectibleID    int32
	Status           GiftStatus
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateGift(ctx context.Context, arg CreateGiftParams) (Gift, error) {
	row := q.db.QueryRow(ctx, createGift,
		arg.ID,
		arg.TelegramGiftID,
		arg.Title,
		arg.Slug,
		arg.OwnerTelegramID,
		arg.UpgradeMessageID,
		arg.Price,
		arg.EmojiID,
		arg.CollectibleID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.TelegramGiftID,
		&i.CollectibleID,
		&i.OwnerTelegramID,
		&i.UpgradeMessageID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.EmojiID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const createGiftAttribute = `-- name: CreateGiftAttribute :one
INSERT INTO gift_attributes (
    gift_id,
    type,
    name,
    rarity_per_mille
) VALUES (
    $1, $2, $3, $4
)
RETURNING gift_id, type, name, rarity_per_mille
`

type CreateGiftAttributeParams struct {
	GiftID         pgtype.UUID
	Type           GiftAttributeType
	Name           string
	RarityPerMille int32
}

func (q *Queries) CreateGiftAttribute(ctx context.Context, arg CreateGiftAttributeParams) (GiftAttribute, error) {
	row := q.db.QueryRow(ctx, createGiftAttribute,
		arg.GiftID,
		arg.Type,
		arg.Name,
		arg.RarityPerMille,
	)
	var i GiftAttribute
	err := row.Scan(
		&i.GiftID,
		&i.Type,
		&i.Name,
		&i.RarityPerMille,
	)
	return i, err
}

const createGiftEvent = `-- name: CreateGiftEvent :one
INSERT INTO gift_events (
    gift_id,
    from_user_id,
    to_user_id
) VALUES (
    $1, $2, $3
)
RETURNING id, gift_id, from_user_id, to_user_id, action, source, related_game_id, description, payload, occurred_at
`

type CreateGiftEventParams struct {
	GiftID     pgtype.UUID
	FromUserID pgtype.Int8
	ToUserID   pgtype.Int8
}

func (q *Queries) CreateGiftEvent(ctx context.Context, arg CreateGiftEventParams) (GiftEvent, error) {
	row := q.db.QueryRow(ctx, createGiftEvent, arg.GiftID, arg.FromUserID, arg.ToUserID)
	var i GiftEvent
	err := row.Scan(
		&i.ID,
		&i.GiftID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Action,
		&i.Source,
		&i.RelatedGameID,
		&i.Description,
		&i.Payload,
		&i.OccurredAt,
	)
	return i, err
}

const getGiftAttributes = `-- name: GetGiftAttributes :many
SELECT gift_id, type, name, rarity_per_mille FROM gift_attributes
WHERE gift_id = $1
`

func (q *Queries) GetGiftAttributes(ctx context.Context, giftID pgtype.UUID) ([]GiftAttribute, error) {
	rows, err := q.db.Query(ctx, getGiftAttributes, giftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GiftAttribute
	for rows.Next() {
		var i GiftAttribute
		if err := rows.Scan(
			&i.GiftID,
			&i.Type,
			&i.Name,
			&i.RarityPerMille,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGiftByID = `-- name: GetGiftByID :one
SELECT id, telegram_gift_id, collectible_id, owner_telegram_id, upgrade_message_id, title, slug, price, emoji_id, status, created_at, updated_at, withdrawn_at
  FROM gifts
 WHERE id = $1
`

func (q *Queries) GetGiftByID(ctx context.Context, id pgtype.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, getGiftByID, id)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.TelegramGiftID,
		&i.CollectibleID,
		&i.OwnerTelegramID,
		&i.UpgradeMessageID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.EmojiID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const getGiftEvents = `-- name: GetGiftEvents :many
SELECT id, gift_id, from_user_id, to_user_id, action, source, related_game_id, description, payload, occurred_at FROM gift_events
WHERE gift_id = $1
ORDER BY occurred_at DESC
LIMIT $2
OFFSET $3
`

type GetGiftEventsParams struct {
	GiftID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetGiftEvents(ctx context.Context, arg GetGiftEventsParams) ([]GiftEvent, error) {
	rows, err := q.db.Query(ctx, getGiftEvents, arg.GiftID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GiftEvent
	for rows.Next() {
		var i GiftEvent
		if err := rows.Scan(
			&i.ID,
			&i.GiftID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Action,
			&i.Source,
			&i.RelatedGameID,
			&i.Description,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGiftsByIDs = `-- name: GetGiftsByIDs :many
SELECT id, telegram_gift_id, collectible_id, owner_telegram_id, upgrade_message_id, title, slug, price, emoji_id, status, created_at, updated_at, withdrawn_at
  FROM gifts
 WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetGiftsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Gift, error) {
	rows, err := q.db.Query(ctx, getGiftsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gift
	for rows.Next() {
		var i Gift
		if err := rows.Scan(
			&i.ID,
			&i.TelegramGiftID,
			&i.CollectibleID,
			&i.OwnerTelegramID,
			&i.UpgradeMessageID,
			&i.Title,
			&i.Slug,
			&i.Price,
			&i.EmojiID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGifts = `-- name: GetUserGifts :many
SELECT id, telegram_gift_id, collectible_id, owner_telegram_id, upgrade_message_id, title, slug, price, emoji_id, status, created_at, updated_at, withdrawn_at
  FROM gifts
 WHERE owner_telegram_id = $1
 ORDER BY created_at DESC
 LIMIT  $2
 OFFSET $3
`

type GetUserGiftsParams struct {
	OwnerTelegramID int64
	Limit           int32
	Offset          int32
}

func (q *Queries) GetUserGifts(ctx context.Context, arg GetUserGiftsParams) ([]Gift, error) {
	rows, err := q.db.Query(ctx, getUserGifts, arg.OwnerTelegramID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gift
	for rows.Next() {
		var i Gift
		if err := rows.Scan(
			&i.ID,
			&i.TelegramGiftID,
			&i.CollectibleID,
			&i.OwnerTelegramID,
			&i.UpgradeMessageID,
			&i.Title,
			&i.Slug,
			&i.Price,
			&i.EmojiID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGiftsCount = `-- name: GetUserGiftsCount :one
SELECT COUNT(*)
  FROM gifts
 WHERE owner_telegram_id = $1
`

func (q *Queries) GetUserGiftsCount(ctx context.Context, ownerTelegramID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getUserGiftsCount, ownerTelegramID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markGiftForWithdrawal = `-- name: MarkGiftForWithdrawal :one
UPDATE gifts 
SET status = 'withdraw_pending', withdraw_requested = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'owned'
RETURNING id, telegram_gift_id, collectible_id, owner_telegram_id, upgrade_message_id, title, slug, price, emoji_id, status, created_at, updated_at, withdrawn_at
`

func (q *Queries) MarkGiftForWithdrawal(ctx context.Context, id pgtype.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, markGiftForWithdrawal, id)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.TelegramGiftID,
		&i.CollectibleID,
		&i.OwnerTelegramID,
		&i.UpgradeMessageID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.EmojiID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const saveGiftWithPrice = `-- name: SaveGiftWithPrice :one
UPDATE gifts 
SET price = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, telegram_gift_id, collectible_id, owner_telegram_id, upgrade_message_id, title, slug, price, emoji_id, status, created_at, updated_at, withdrawn_at
`

type SaveGiftWithPriceParams struct {
	ID    pgtype.UUID
	Price float64
}

func (q *Queries) SaveGiftWithPrice(ctx context.Context, arg SaveGiftWithPriceParams) (Gift, error) {
	row := q.db.QueryRow(ctx, saveGiftWithPrice, arg.ID, arg.Price)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.TelegramGiftID,
		&i.CollectibleID,
		&i.OwnerTelegramID,
		&i.UpgradeMessageID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.EmojiID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const stakeGiftForGame = `-- name: StakeGiftForGame :one
UPDATE gifts 
SET status = 'in_game', updated_at = NOW()
WHERE id = $1 AND status = 'owned'
RETURNING id, telegram_gift_id, collectible_id, owner_telegram_id, upgrade_message_id, title, slug, price, emoji_id, status, created_at, updated_at, withdrawn_at
`

func (q *Queries) StakeGiftForGame(ctx context.Context, id pgtype.UUID) (Gift, error) {
	row := q.db.QueryRow(ctx, stakeGiftForGame, id)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.TelegramGiftID,
		&i.CollectibleID,
		&i.OwnerTelegramID,
		&i.UpgradeMessageID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.EmojiID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const updateGiftOwner = `-- name: UpdateGiftOwner :one
UPDATE gifts 
SET owner_telegram_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, telegram_gift_id, collectible_id, owner_telegram_id, upgrade_message_id, title, slug, price, emoji_id, status, created_at, updated_at, withdrawn_at
`

type UpdateGiftOwnerParams struct {
	ID              pgtype.UUID
	OwnerTelegramID int64
}

func (q *Queries) UpdateGiftOwner(ctx context.Context, arg UpdateGiftOwnerParams) (Gift, error) {
	row := q.db.QueryRow(ctx, updateGiftOwner, arg.ID, arg.OwnerTelegramID)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.TelegramGiftID,
		&i.CollectibleID,
		&i.OwnerTelegramID,
		&i.UpgradeMessageID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.EmojiID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const updateGiftStatus = `-- name: UpdateGiftStatus :one
UPDATE gifts 
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, telegram_gift_id, collectible_id, owner_telegram_id, upgrade_message_id, title, slug, price, emoji_id, status, created_at, updated_at, withdrawn_at
`

type UpdateGiftStatusParams struct {
	ID     pgtype.UUID
	Status GiftStatus
}

func (q *Queries) UpdateGiftStatus(ctx context.Context, arg UpdateGiftStatusParams) (Gift, error) {
	row := q.db.QueryRow(ctx, updateGiftStatus, arg.ID, arg.Status)
	var i Gift
	err := row.Scan(
		&i.ID,
		&i.TelegramGiftID,
		&i.CollectibleID,
		&i.OwnerTelegramID,
		&i.UpgradeMessageID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.EmojiID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}
